# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Street-FootBall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Street-FootBall
pod 'AFNetworking', '~> 3.1'
 pod 'GoogleMaps'
  pod 'GooglePlaces'
pod 'MBProgressHUD', '~> 1.0'
pod ‘Alamofire’
pod 'AlamofireActivityLogger'
pod ‘ObjectMapper’
pod 'NVActivityIndicatorView'
pod 'Bolts-Swift'
pod 'Kingfisher'
end
